import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy · BrickThink',
  description:
    'How BrickThink collects, uses, and discloses personal information for users of brickthink.io and the BrickThink platform.',
};

const LAST_UPDATED = '15 May 2026';

export default function PrivacyPage() {
  return (
    <div className="min-h-[100dvh] bg-[#FAF7F1] text-zinc-900">
      <LegalTopBar />
      <main id="main" className="mx-auto max-w-2xl px-6 py-12 md:py-20">
        <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
          Legal · Last updated {LAST_UPDATED}
        </p>
        <h1 className="mt-3 text-4xl font-semibold leading-[1.05] tracking-tight text-zinc-950 md:text-5xl">
          Privacy Policy
        </h1>

        <article className="mt-10 space-y-10 text-[15px] leading-relaxed text-zinc-700">
          <Block>
            <P>
              Brick Think (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) is committed to
              protecting your privacy. This Privacy Policy explains how your personal information is
              collected, used, and disclosed by Brick Think.
            </P>
            <P>
              This Privacy Policy applies to our website and its associated subdomains
              (collectively, our &ldquo;Service&rdquo;) alongside our application, Brick Think. By
              accessing or using our Service, you signify that you have read, understood, and agree
              to our collection, storage, use, and disclosure of your personal information as
              described in this Privacy Policy and our Terms of Service.
            </P>
          </Block>

          <Section heading="Definitions and key terms">
            <P>
              To help explain things as clearly as possible in this Privacy Policy, every time any
              of these terms are referenced, are strictly defined as:
            </P>
            <UL>
              <li>
                <Em>Cookie:</Em> small amount of data generated by a website and saved by your web
                browser. It is used to identify your browser, provide analytics, remember
                information about you such as your language preference or login information.
              </li>
              <li>
                <Em>Company:</Em> when this policy mentions &ldquo;Company,&rdquo; &ldquo;we,&rdquo;
                &ldquo;us,&rdquo; or &ldquo;our,&rdquo; it refers to Brick Think, that is
                responsible for your information under this Privacy Policy.
              </li>
              <li>
                <Em>Country:</Em> where Brick Think or the owners/founders of Brick Think are based,
                in this case Switzerland.
              </li>
              <li>
                <Em>Customer:</Em> refers to the company, organization, or person that signs up to
                use the Brick Think Service to manage the relationships with your consumers or
                service users.
              </li>
              <li>
                <Em>Device:</Em> any internet-connected device such as a phone, tablet, computer or
                any other device that can be used to visit Brick Think and use the services.
              </li>
              <li>
                <Em>IP address:</Em> Every device connected to the Internet is assigned a number
                known as an Internet protocol (IP) address. These numbers are usually assigned in
                geographic blocks. An IP address can often be used to identify the location from
                which a device is connecting to the Internet.
              </li>
              <li>
                <Em>Personnel:</Em> refers to those individuals who are employed by Brick Think or
                are under contract to perform a service on behalf of one of the parties.
              </li>
              <li>
                <Em>Personal Data:</Em> any information that directly, indirectly, or in connection
                with other information &mdash; including a personal identification number &mdash;
                allows for the identification or identifiability of a natural person.
              </li>
              <li>
                <Em>Service:</Em> refers to the service provided by Brick Think as described in the
                relative terms (if available) and on this platform.
              </li>
              <li>
                <Em>Third-party service:</Em> refers to advertisers, contest sponsors, promotional
                and marketing partners, and others who provide our content or whose products or
                services we think may interest you.
              </li>
              <li>
                <Em>Website:</Em> Brick Think&apos;s site, which can be accessed via this URL:{' '}
                <a
                  href="https://www.brickthink.io/"
                  className="underline-offset-2 hover:underline"
                >
                  https://www.brickthink.io/
                </a>
                .
              </li>
              <li>
                <Em>You:</Em> a person or entity that is registered with Brick Think to use the
                Services.
              </li>
            </UL>
          </Section>

          <Section heading="Information automatically collected">
            <P>
              There is some information &mdash; like your Internet Protocol (IP) address and/or
              browser and device characteristics &mdash; that is collected automatically when you
              visit our platform. This information may be used to connect your computer to the
              Internet. Other information collected automatically could be a login, e-mail address,
              password, computer and connection information such as browser plug-in types and
              versions and time zone setting, operating systems and platforms, purchase history (we
              sometimes aggregate with similar information from other Users), the full Uniform
              Resource Locator (URL) clickstream to, through, and from our Website that may include
              date and time; cookie number; parts of the site you viewed or searched for; and the
              phone number you used to call our Customer Services.
            </P>
            <P>
              We may also use browser data such as cookies, Flash cookies (also known as Flash Local
              Shared Objects), or similar data on certain parts of our Website for fraud prevention
              and other purposes. During your visits, we may use software tools such as JavaScript
              to measure and collect session information including page response times, download
              errors, length of visits to certain pages, page interaction information (such as
              scrolling, clicks, and mouse-overs), and methods used to browse away from the page.
              We may also collect technical information to help us identify your device for fraud
              prevention and diagnostic purposes.
            </P>
            <P>
              We automatically collect certain information when you visit, use, or navigate the
              platform. This information does not reveal your specific identity (like your name or
              contact information) but may include device and usage information, such as your IP
              address, browser and device characteristics, operating system, language preferences,
              referring URLs, device name, country, location, information about who and when you
              use our and other technical information. This information is primarily needed to
              maintain the security and operation of our platform, and for our internal analytics
              and reporting purposes.
            </P>
          </Section>

          <Section heading="Sale of business">
            <P>
              We reserve the right to transfer information to a third party in the event of a sale,
              merger, or other transfer of all or substantially all of the assets of Brick Think or
              any of its Corporate Affiliates (as defined herein), or that portion of Brick Think or
              any of its Corporate Affiliates to which the Service relates, or in the event that we
              discontinue our business or file a petition or have filed against us a petition in
              bankruptcy, reorganization, or similar proceeding, provided that the third party
              agrees to adhere to the terms of this Privacy Policy.
            </P>
          </Section>

          <Section heading="Affiliates">
            <P>
              We may disclose information (including personal information) about you to our
              Corporate Affiliates. For purposes of this Privacy Policy, &ldquo;Corporate
              Affiliate&rdquo; means any person or entity which directly or indirectly controls, is
              controlled by, or is under common control with Brick Think, whether by ownership or
              otherwise. Any information relating to you that we provide to our Corporate Affiliates
              will be treated by those Corporate Affiliates in accordance with the terms of this
              Privacy Policy.
            </P>
          </Section>

          <Section heading="Governing law">
            <P>
              This Privacy Policy is governed by the laws of Switzerland without regard to its
              conflict of laws provision. You consent to the exclusive jurisdiction of the courts
              in connection with any action or dispute arising between the parties under or in
              connection with this Privacy Policy except for those individuals who may have rights
              to make claims under Privacy Shield, or the Swiss-US framework.
            </P>
            <P>
              The laws of Switzerland, excluding its conflicts of law rules, shall govern this
              Agreement and your use of the website. Your use of the website may also be subject to
              other local, state, national, or international laws.
            </P>
            <P>
              By using Brick Think or contacting us directly, you signify your acceptance of this
              Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with
              our website, or use our services. Continued use of the website, direct engagement
              with us, or following the posting of changes to this Privacy Policy that do not
              significantly affect the use or disclosure of your personal information will mean
              that you accept those changes.
            </P>
          </Section>

          <Section heading="Your consent">
            <P>
              We&apos;ve updated our Privacy Policy to provide you with complete transparency into
              what is being set when you visit our site and how it&apos;s being used. By using our
              website, registering an account, or making a purchase, you hereby consent to our
              Privacy Policy and agree to its terms.
            </P>
          </Section>

          <Section heading="Links to other websites">
            <P>
              This Privacy Policy applies only to the Services. The Services may contain links to
              other websites not operated or controlled by Brick Think. We are not responsible for
              the content, accuracy, or opinions expressed in such websites, and such websites are
              not investigated, monitored, or checked for accuracy or completeness by us. Please
              remember that when you use a link to go from the Services to another website, our
              Privacy Policy is no longer in effect. Your browsing and interaction on any other
              website, including those that have a link on our platform, is subject to that
              website&apos;s own rules and policies. Such third parties may use their own cookies
              or other methods to collect information about you.
            </P>
          </Section>

          <Section heading="Cookies">
            <P>
              Brick Think uses &ldquo;Cookies&rdquo; to identify the areas of our website that you
              have visited. A Cookie is a small piece of data stored on your computer or mobile
              device by your web browser. We use Cookies to enhance the performance and
              functionality of our website but are non-essential to their use. However, without
              these cookies, certain functionality like videos may become unavailable or you would
              be required to enter your login details every time you visit the website as we would
              not be able to remember that you had logged in previously. Most web browsers can be
              set to disable the use of Cookies. However, if you disable Cookies, you may not be
              able to access functionality on our website correctly or at all. We never place
              Personally Identifiable Information in Cookies.
            </P>
          </Section>

          <Section heading="Blocking and disabling cookies and similar technologies">
            <P>
              Wherever you&apos;re located you may also set your browser to block cookies and
              similar technologies, but this action may block our essential cookies and prevent our
              website from functioning properly, and you may not be able to fully utilize all of
              its features and services. You should also be aware that you may also lose some saved
              information (e.g. saved login details, site preferences) if you block cookies on your
              browser. Different browsers make different controls available to you. Disabling a
              cookie or category of cookie does not delete the cookie from your browser, you will
              need to do this yourself from within your browser; you should visit your
              browser&apos;s help menu for more information.
            </P>
          </Section>

          <Section heading="Payment details">
            <P>
              In respect to any credit card or other payment processing details you have provided
              us, we commit that this confidential information will be stored in the most secure
              manner possible.
            </P>
          </Section>

          <Section heading="Kids' privacy">
            <P>
              We do not address anyone under the age of 13. We do not knowingly collect personally
              identifiable information from anyone under the age of 13. If you are a parent or
              guardian and you are aware that your child has provided us with Personal Data, please
              contact us. If we become aware that we have collected Personal Data from anyone under
              the age of 13 without verification of parental consent, we take steps to remove that
              information from our servers.
            </P>
          </Section>

          <Section heading="Changes to our Privacy Policy">
            <P>
              We may change our Service and policies, and we may need to make changes to this
              Privacy Policy so that they accurately reflect our Service and policies. Unless
              otherwise required by law, we will notify you (for example, through our Service)
              before we make changes to this Privacy Policy and give you an opportunity to review
              them before they go into effect. Then, if you continue to use the Service, you will
              be bound by the updated Privacy Policy. If you do not want to agree to this or any
              updated Privacy Policy, you can delete your account.
            </P>
          </Section>

          <Section heading="Third-party services">
            <P>
              We may display, include, or make available third-party content (including data,
              information, applications, and other products services) or provide links to
              third-party websites or services (&ldquo;Third-Party Services&rdquo;).
            </P>
            <P>
              You acknowledge and agree that Brick Think shall not be responsible for any
              Third-Party Services, including their accuracy, completeness, timeliness, validity,
              copyright compliance, legality, decency, quality, or any other aspect thereof. Brick
              Think does not assume and shall not have any liability or responsibility to you or
              any other person or entity for any Third-Party Services.
            </P>
            <P>
              Third-Party Services and links thereto are provided solely as a convenience to you
              and you access and use them entirely at your own risk and subject to such third
              parties&apos; terms and conditions.
            </P>
          </Section>

          <Section heading="GDPR — information about General Data Protection Regulation">
            <P>
              We may be collecting and using information from you if you are from the European
              Economic Area (EEA), and in this section of our Privacy Policy we are going to
              explain exactly how and why this data is collected, and how we maintain this data
              under protection from being replicated or used in the wrong way.
            </P>

            <SubHeading>What is GDPR?</SubHeading>
            <P>
              GDPR is an EU-wide privacy and data protection law that regulates how EU
              residents&apos; data is protected by companies and enhances the control the EU
              residents have over their personal data.
            </P>
            <P>
              The GDPR is relevant to any globally operating company and not just the EU-based
              businesses and EU residents. Our customers&apos; data is important irrespective of
              where they are located, which is why we have implemented GDPR controls as our
              baseline standard for all our operations worldwide.
            </P>

            <SubHeading>What is personal data?</SubHeading>
            <P>
              Any data that relates to an identifiable or identified individual. GDPR covers a
              broad spectrum of information that could be used on its own, or in combination with
              other pieces of information, to identify a person. Personal data extends beyond a
              person&apos;s name or email address. Some examples include financial information,
              political opinions, genetic data, biometric data, IP addresses, physical address,
              sexual orientation, and ethnicity.
            </P>

            <SubHeading>The data protection principles include requirements such as:</SubHeading>
            <UL>
              <li>
                Personal data collected must be processed in a fair, legal, and transparent way and
                should only be used in a way that a person would reasonably expect.
              </li>
              <li>
                Personal data should only be collected to fulfil a specific purpose and it should
                only be used for that purpose. Organizations must specify why they need the
                personal data when they collect it.
              </li>
              <li>Personal data should be held no longer than necessary to fulfil its purpose.</li>
              <li>
                People covered by the GDPR have the right to access their own personal data. They
                can also request a copy of their data, and that their data be updated, deleted,
                restricted, or moved to another organization.
              </li>
            </UL>

            <SubHeading>Why is GDPR important?</SubHeading>
            <P>
              GDPR adds some new requirements regarding how companies should protect
              individuals&apos; personal data that they collect and process. It also raises the
              stakes for compliance by increasing enforcement and imposing greater fines for
              breach. Beyond these facts it&apos;s simply the right thing to do. At Brick Think we
              strongly believe that your data privacy is very important and we already have solid
              security and privacy practices in place that go beyond the requirements of this new
              regulation.
            </P>

            <SubHeading>
              Individual data subject&apos;s rights — data access, portability and deletion
            </SubHeading>
            <P>
              We are committed to helping our customers meet the data subject rights requirements
              of GDPR. Brick Think processes or stores all personal data in fully vetted, DPA
              compliant vendors. We do store all conversation and personal data for up to 6 years
              unless your account is deleted. In which case, we dispose of all data in accordance
              with our Terms of Service and Privacy Policy, but we will not hold it longer than 60
              days.
            </P>
            <P>
              We are aware that if you are working with EU customers, you need to be able to
              provide them with the ability to access, update, retrieve, and remove personal data.
              We got you. We&apos;ve been set up as self-service from the start and have always
              given you access to your data and your customers&apos; data. Our customer support
              team is here for you to answer any questions you might have about working with the
              API.
            </P>
          </Section>

          <Section heading="California residents">
            <P>
              The California Consumer Privacy Act (CCPA) requires us to disclose categories of
              Personal Information we collect and how we use it, the categories of sources from
              whom we collect Personal Information, and the third parties with whom we share it,
              which we have explained above.
            </P>
            <P>
              We are also required to communicate information about rights California residents
              have under California law. You may exercise the following rights:
            </P>
            <UL>
              <li>
                <Em>Right to know and access.</Em> You may submit a verifiable request for
                information regarding the: (1) categories of Personal Information we collect, use,
                or share; (2) purposes for which categories of Personal Information are collected
                or used by us; (3) categories of sources from which we collect Personal
                Information; and (4) specific pieces of Personal Information we have collected
                about you.
              </li>
              <li>
                <Em>Right to equal service.</Em> We will not discriminate against you if you
                exercise your privacy rights.
              </li>
              <li>
                <Em>Right to delete.</Em> You may submit a verifiable request to close your account
                and we will delete Personal Information about you that we have collected.
              </li>
              <li>
                Request that a business that sells a consumer&apos;s personal data, not sell the
                consumer&apos;s personal data.
              </li>
            </UL>
            <P>
              If you make a request, we have one month to respond to you. If you would like to
              exercise any of these rights, please contact us. We do not sell the Personal
              Information of our users.
            </P>
          </Section>

          <Section heading="Contact us">
            <P>Don&apos;t hesitate to contact us if you have any questions.</P>
            <P>
              Via email:{' '}
              <a
                href="mailto:redacted@example.com"
                className="font-medium text-zinc-900 underline-offset-2 hover:underline"
              >
                redacted@example.com
              </a>
            </P>
          </Section>
        </article>

        <LegalFooterNav />
      </main>
    </div>
  );
}

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section className="space-y-4">
      <h2 className="text-2xl font-semibold tracking-tight text-zinc-950">{heading}</h2>
      {children}
    </section>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="mt-6 font-mono text-[11px] uppercase tracking-[0.18em] text-zinc-500">
      {children}
    </h3>
  );
}

function Block({ children }: { children: React.ReactNode }) {
  return <div className="space-y-4">{children}</div>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p>{children}</p>;
}

function UL({ children }: { children: React.ReactNode }) {
  return <ul className="list-disc space-y-2 pl-6">{children}</ul>;
}

function Em({ children }: { children: React.ReactNode }) {
  return <span className="font-medium text-zinc-900">{children}</span>;
}

function LegalTopBar() {
  return (
    <header className="sticky top-0 z-30 border-b border-zinc-900/5 bg-[#FAF7F1]/80 backdrop-blur-md">
      <div className="mx-auto flex h-14 max-w-2xl items-center justify-between px-6">
        <Link href="/" className="flex items-center gap-2 text-zinc-900">
          <BrickGlyph />
          <span className="text-[15px] font-semibold tracking-tight">BrickThink</span>
        </Link>
        <Link
          href="/sign-in"
          className="text-sm text-zinc-600 transition-colors hover:text-zinc-900"
        >
          Sign in
        </Link>
      </div>
    </header>
  );
}

function LegalFooterNav() {
  return (
    <nav
      aria-label="Legal"
      className="mt-16 flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-zinc-900/10 pt-6 text-[13px] text-zinc-600"
    >
      <Link href="/" className="hover:text-zinc-900">
        Home
      </Link>
      <Link href="/terms" className="hover:text-zinc-900">
        Terms &amp; Conditions
      </Link>
      <Link href="/sign-in" className="hover:text-zinc-900">
        Sign in
      </Link>
      <a
        href="mailto:redacted@example.com"
        className="hover:text-zinc-900"
      >
        Contact
      </a>
    </nav>
  );
}

function BrickGlyph() {
  return (
    <span className="relative inline-flex h-7 w-7 items-center justify-center rounded-md bg-[#c0613d] shadow-[inset_0_0_0_1px_rgba(0,0,0,0.18),0_2px_0_rgba(255,255,255,0.4)_inset]">
      <span className="absolute left-1/2 top-1.5 h-1.5 w-1.5 -translate-x-1/2 rounded-full bg-black/20" />
      <span className="absolute right-1/4 top-1.5 h-1.5 w-1.5 translate-x-1/2 rounded-full bg-black/20" />
    </span>
  );
}
