-- supabase/migrations/20260522110000_seed_site_admin.sql
-- (Retained for migration-history continuity — intentionally a no-op.)
--
-- This migration originally promoted a hardcoded maintainer email to site admin.
-- Admin is no longer seeded by migrations: there is no hardcoded admin, and a
-- fresh deploy has zero admins until the operator grants one. Bootstrapping is a
-- one-time, no-privilege SQL step run after first sign-in — see README
-- "Granting site admin":
--
--   insert into public.site_admin_emails (email) values ('you@example.com')
--   on conflict (email) do nothing;
--   update public.profiles set is_site_admin = true where email = 'you@example.com';
--
-- The data-driven allowlist + promotion trigger in
-- 20260606090000_site_admin_self_healing.sql is the mechanism. This file
-- deliberately does nothing.
--
-- (An interim revision sourced the email from an `app.site_admin_emails` GUC,
-- but the `postgres` role can't persist custom GUCs on Supabase cloud or the
-- local CLI stack — non-superuser — so that approach was dropped for the
-- manual-grant path above.)
