import type { BrickDefinition } from './types';

export const CANONICAL_BRICKS: readonly BrickDefinition[] = [
  { code: 'block-green-medium-left', name: 'Block green medium left', category: 'brick', width: 180, height: 156, image: '/bricks/block-green-medium-left.png' },
  { code: 'block-green-medium-right', name: 'Block green medium right', category: 'brick', width: 180, height: 156, image: '/bricks/block-green-medium-right.png' },
  { code: 'block-navy-medium-left', name: 'Block navy medium left', category: 'brick', width: 180, height: 156, image: '/bricks/block-navy-medium-left.png' },
  { code: 'block-navy-medium-right', name: 'Block navy medium right', category: 'brick', width: 180, height: 156, image: '/bricks/block-navy-medium-right.png' },
  { code: 'block-pink-medium-left', name: 'Block pink medium left', category: 'brick', width: 180, height: 156, image: '/bricks/block-pink-medium-left.png' },
  { code: 'block-pink-medium-right', name: 'Block pink medium right', category: 'brick', width: 180, height: 156, image: '/bricks/block-pink-medium-right.png' },
  { code: 'block-red-medium-left', name: 'Block red medium left', category: 'brick', width: 180, height: 156, image: '/bricks/block-red-medium-left.png' },
  { code: 'block-red-medium-right', name: 'Block red medium right', category: 'brick', width: 180, height: 156, image: '/bricks/block-red-medium-right.png' },
  { code: 'block-yellow-medium', name: 'Block yellow medium', category: 'brick', width: 180, height: 156, image: '/bricks/block-yellow-medium.png' },
  { code: 'blockarch-grey-medium-left', name: 'Blockarch grey medium left', category: 'brick', width: 180, height: 156, image: '/bricks/blockarch-grey-medium-left.png' },
  { code: 'blockarch-grey-medium-right', name: 'Blockarch grey medium right', category: 'brick', width: 180, height: 156, image: '/bricks/blockarch-grey-medium-right.png' },
  { code: 'corner-grey-large-left', name: 'Corner grey large left', category: 'slope', width: 300, height: 275, image: '/bricks/corner-grey-large-left.png' },
  { code: 'corner-grey-large-right', name: 'Corner grey large right', category: 'slope', width: 300, height: 275, image: '/bricks/corner-grey-large-right.png' },
  { code: 'corner-grey-large-top-left', name: 'Corner grey large top left', category: 'slope', width: 300, height: 246, image: '/bricks/corner-grey-large-top-left.png' },
  { code: 'corner-grey-large-top-right', name: 'Corner grey large top right', category: 'slope', width: 300, height: 246, image: '/bricks/corner-grey-large-top-right.png' },
  { code: 'corner-orange-small', name: 'Corner orange small', category: 'slope', width: 100, height: 98, image: '/bricks/corner-orange-small.png' },
  { code: 'corner-upside-grey-large-left', name: 'Corner upside grey large left', category: 'slope', width: 300, height: 245, image: '/bricks/corner-upside-grey-large-left.png' },
  { code: 'corner-upside-grey-large-right', name: 'Corner upside grey large right', category: 'slope', width: 300, height: 245, image: '/bricks/corner-upside-grey-large-right.png' },
  { code: 'corner-upside-grey-large-top-left', name: 'Corner upside grey large top left', category: 'slope', width: 300, height: 275, image: '/bricks/corner-upside-grey-large-top-left.png' },
  { code: 'corner-upside-grey-large-top-right', name: 'Corner upside grey large top right', category: 'slope', width: 300, height: 275, image: '/bricks/corner-upside-grey-large-top-right.png' },
  { code: 'doubleblock-green-medium-left', name: 'Doubleblock green medium left', category: 'brick', width: 180, height: 149, image: '/bricks/doubleblock-green-medium-left.png' },
  { code: 'doubleblock-green-medium-right', name: 'Doubleblock green medium right', category: 'brick', width: 180, height: 149, image: '/bricks/doubleblock-green-medium-right.png' },
  { code: 'flat-1-black-large-left', name: 'Flat 1 black large left', category: 'plate', width: 300, height: 190, image: '/bricks/flat-1-black-large-left.png' },
  { code: 'flat-1-black-large-right', name: 'Flat 1 black large right', category: 'plate', width: 300, height: 189, image: '/bricks/flat-1-black-large-right.png' },
  { code: 'flat-2-orange-small-left', name: 'Flat 2 orange small left', category: 'plate', width: 100, height: 74, image: '/bricks/flat-2-orange-small-left.png' },
  { code: 'flat-2-orange-small-right', name: 'Flat 2 orange small right', category: 'plate', width: 100, height: 74, image: '/bricks/flat-2-orange-small-right.png' },
  { code: 'flat-3-orange-medium-left', name: 'Flat 3 orange medium left', category: 'plate', width: 180, height: 128, image: '/bricks/flat-3-orange-medium-left.png' },
  { code: 'flat-3-orange-medium-right', name: 'Flat 3 orange medium right', category: 'plate', width: 180, height: 128, image: '/bricks/flat-3-orange-medium-right.png' },
  { code: 'flat-4-yellow-long-left', name: 'Flat 4 yellow long left', category: 'plate', width: 260, height: 173, image: '/bricks/flat-4-yellow-long-left.png' },
  { code: 'flat-4-yellow-long-right', name: 'Flat 4 yellow long right', category: 'plate', width: 260, height: 173, image: '/bricks/flat-4-yellow-long-right.png' },
  { code: 'flat-5-white-longer-left', name: 'Flat 5 white longer left', category: 'plate', width: 340, height: 213, image: '/bricks/flat-5-white-longer-left.png' },
  { code: 'flat-5-white-longer-right', name: 'Flat 5 white longer right', category: 'plate', width: 340, height: 213, image: '/bricks/flat-5-white-longer-right.png' },
  { code: 'flower-green-small', name: 'Flower green small', category: 'decorative', width: 100, height: 94, image: '/bricks/flower-green-small.png' },
  { code: 'flower-pink-small', name: 'Flower pink small', category: 'decorative', width: 100, height: 94, image: '/bricks/flower-pink-small.png' },
  { code: 'piece-body', name: 'Piece body', category: 'figure', width: 150, height: 158, image: '/bricks/piece-body.png' },
  { code: 'piece-connector-left', name: 'Piece connector left', category: 'connector', width: 150, height: 141, image: '/bricks/piece-connector-left.png' },
  { code: 'piece-connector-right', name: 'Piece connector right', category: 'connector', width: 150, height: 141, image: '/bricks/piece-connector-right.png' },
  { code: 'piece-connector-top-left', name: 'Piece connector top left', category: 'connector', width: 150, height: 141, image: '/bricks/piece-connector-top-left.png' },
  { code: 'piece-connector-top-right', name: 'Piece connector top right', category: 'connector', width: 150, height: 141, image: '/bricks/piece-connector-top-right.png' },
  { code: 'piece-crossarch-holder', name: 'Piece crossarch holder', category: 'specialty', width: 150, height: 151, image: '/bricks/piece-crossarch-holder.png' },
  { code: 'piece-crossarch', name: 'Piece crossarch', category: 'specialty', width: 150, height: 117, image: '/bricks/piece-crossarch.png' },
  { code: 'piece-eyeblock-left', name: 'Piece eyeblock left', category: 'specialty', width: 150, height: 160, image: '/bricks/piece-eyeblock-left.png' },
  { code: 'piece-eyeblock-right', name: 'Piece eyeblock right', category: 'specialty', width: 150, height: 160, image: '/bricks/piece-eyeblock-right.png' },
  { code: 'piece-flag', name: 'Piece flag', category: 'decorative', width: 150, height: 136, image: '/bricks/piece-flag.png' },
  { code: 'piece-flagpole', name: 'Piece flagpole', category: 'decorative', width: 150, height: 280, image: '/bricks/piece-flagpole.png' },
  { code: 'piece-head', name: 'Piece head', category: 'figure', width: 150, height: 161, image: '/bricks/piece-head.png' },
  { code: 'piece-ladder', name: 'Piece ladder', category: 'specialty', width: 150, height: 170, image: '/bricks/piece-ladder.png' },
  { code: 'post-grey-small', name: 'Post grey small', category: 'specialty', width: 100, height: 87, image: '/bricks/post-grey-small.png' },
  { code: 'singleblock-green-small-left', name: 'Singleblock green small left', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-green-small-left.png' },
  { code: 'singleblock-green-small-right', name: 'Singleblock green small right', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-green-small-right.png' },
  { code: 'singleblock-grey-small-left', name: 'Singleblock grey small left', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-grey-small-left.png' },
  { code: 'singleblock-grey-small-right', name: 'Singleblock grey small right', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-grey-small-right.png' },
  { code: 'singleblock-lime-small-left', name: 'Singleblock lime small left', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-lime-small-left.png' },
  { code: 'singleblock-lime-small-right', name: 'Singleblock lime small right', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-lime-small-right.png' },
  { code: 'singleblock-pink-small-left', name: 'Singleblock pink small left', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-pink-small-left.png' },
  { code: 'singleblock-pink-small-right', name: 'Singleblock pink small right', category: 'brick', width: 100, height: 98, image: '/bricks/singleblock-pink-small-right.png' },
  { code: 'squareblock-green-medium', name: 'Squareblock green medium', category: 'brick', width: 180, height: 165, image: '/bricks/squareblock-green-medium.png' },
];

export function findCanonicalBrick(code: string): BrickDefinition | undefined {
  return CANONICAL_BRICKS.find((b) => b.code === code);
}
