import type { BrickDefinition } from './types';

const C = {
  brick: '#c0613d',
  plate: '#7a8b66',
  slope: '#6c7693',
  round: '#d6a04b',
  window: '#9bb7d4',
  door: '#8c6a52',
  decorative: '#a8557a',
  figure: '#cfa663',
  connector: '#3f4753',
  specialty: '#525c69',
} as const;

export const CANONICAL_BRICKS: readonly BrickDefinition[] = [
  // Standard bricks (10)
  {
    code: 'brick-1x1',
    name: '1 by 1 brick',
    category: 'brick',
    studsX: 1,
    studsY: 1,
    defaultColour: C.brick,
  },
  {
    code: 'brick-1x2',
    name: '1 by 2 brick',
    category: 'brick',
    studsX: 1,
    studsY: 2,
    defaultColour: C.brick,
  },
  {
    code: 'brick-1x3',
    name: '1 by 3 brick',
    category: 'brick',
    studsX: 1,
    studsY: 3,
    defaultColour: C.brick,
  },
  {
    code: 'brick-1x4',
    name: '1 by 4 brick',
    category: 'brick',
    studsX: 1,
    studsY: 4,
    defaultColour: C.brick,
  },
  {
    code: 'brick-1x6',
    name: '1 by 6 brick',
    category: 'brick',
    studsX: 1,
    studsY: 6,
    defaultColour: C.brick,
  },
  {
    code: 'brick-1x8',
    name: '1 by 8 brick',
    category: 'brick',
    studsX: 1,
    studsY: 8,
    defaultColour: C.brick,
  },
  {
    code: 'brick-2x2',
    name: '2 by 2 brick',
    category: 'brick',
    studsX: 2,
    studsY: 2,
    defaultColour: C.brick,
  },
  {
    code: 'brick-2x3',
    name: '2 by 3 brick',
    category: 'brick',
    studsX: 2,
    studsY: 3,
    defaultColour: C.brick,
  },
  {
    code: 'brick-2x4',
    name: '2 by 4 brick',
    category: 'brick',
    studsX: 2,
    studsY: 4,
    defaultColour: C.brick,
  },
  {
    code: 'brick-2x6',
    name: '2 by 6 brick',
    category: 'brick',
    studsX: 2,
    studsY: 6,
    defaultColour: C.brick,
  },

  // Plates (8)
  {
    code: 'plate-1x1',
    name: '1 by 1 plate',
    category: 'plate',
    studsX: 1,
    studsY: 1,
    defaultColour: C.plate,
  },
  {
    code: 'plate-1x2',
    name: '1 by 2 plate',
    category: 'plate',
    studsX: 1,
    studsY: 2,
    defaultColour: C.plate,
  },
  {
    code: 'plate-1x4',
    name: '1 by 4 plate',
    category: 'plate',
    studsX: 1,
    studsY: 4,
    defaultColour: C.plate,
  },
  {
    code: 'plate-1x6',
    name: '1 by 6 plate',
    category: 'plate',
    studsX: 1,
    studsY: 6,
    defaultColour: C.plate,
  },
  {
    code: 'plate-2x2',
    name: '2 by 2 plate',
    category: 'plate',
    studsX: 2,
    studsY: 2,
    defaultColour: C.plate,
  },
  {
    code: 'plate-2x4',
    name: '2 by 4 plate',
    category: 'plate',
    studsX: 2,
    studsY: 4,
    defaultColour: C.plate,
  },
  {
    code: 'plate-2x6',
    name: '2 by 6 plate',
    category: 'plate',
    studsX: 2,
    studsY: 6,
    defaultColour: C.plate,
  },
  {
    code: 'plate-2x8',
    name: '2 by 8 plate',
    category: 'plate',
    studsX: 2,
    studsY: 8,
    defaultColour: C.plate,
  },

  // Slopes (5)
  {
    code: 'slope-2x2',
    name: '2 by 2 slope',
    category: 'slope',
    studsX: 2,
    studsY: 2,
    defaultColour: C.slope,
  },
  {
    code: 'slope-2x4',
    name: '2 by 4 slope',
    category: 'slope',
    studsX: 2,
    studsY: 4,
    defaultColour: C.slope,
  },
  {
    code: 'slope-corner-2x2',
    name: '2 by 2 corner slope',
    category: 'slope',
    studsX: 2,
    studsY: 2,
    defaultColour: C.slope,
  },
  {
    code: 'slope-inverted-2x2',
    name: '2 by 2 inverted slope',
    category: 'slope',
    studsX: 2,
    studsY: 2,
    defaultColour: C.slope,
  },
  {
    code: 'slope-curve-2x2',
    name: '2 by 2 curved slope',
    category: 'slope',
    studsX: 2,
    studsY: 2,
    defaultColour: C.slope,
  },

  // Round (4)
  {
    code: 'round-1x1',
    name: '1 by 1 round',
    category: 'round',
    studsX: 1,
    studsY: 1,
    defaultColour: C.round,
  },
  {
    code: 'round-2x2',
    name: '2 by 2 round',
    category: 'round',
    studsX: 2,
    studsY: 2,
    defaultColour: C.round,
  },
  {
    code: 'round-tall-1x1',
    name: '1 by 1 tall round',
    category: 'round',
    studsX: 1,
    studsY: 1,
    defaultColour: C.round,
  },
  {
    code: 'cone-2x2',
    name: '2 by 2 cone',
    category: 'round',
    studsX: 2,
    studsY: 2,
    defaultColour: C.round,
  },

  // Window and door (3)
  {
    code: 'window-1x2',
    name: '1 by 2 window',
    category: 'window',
    studsX: 1,
    studsY: 2,
    defaultColour: C.window,
  },
  {
    code: 'window-arched-1x2',
    name: '1 by 2 arched window',
    category: 'window',
    studsX: 1,
    studsY: 2,
    defaultColour: C.window,
  },
  {
    code: 'door-1x2',
    name: '1 by 2 door',
    category: 'door',
    studsX: 1,
    studsY: 2,
    defaultColour: C.door,
  },

  // Decorative (8)
  {
    code: 'flower-1x1',
    name: 'Flower',
    category: 'decorative',
    studsX: 1,
    studsY: 1,
    defaultColour: C.decorative,
  },
  {
    code: 'leaf-1x1',
    name: 'Leaf',
    category: 'decorative',
    studsX: 1,
    studsY: 1,
    defaultColour: C.decorative,
  },
  {
    code: 'tree-2x2',
    name: 'Tree',
    category: 'decorative',
    studsX: 2,
    studsY: 2,
    defaultColour: C.decorative,
  },
  {
    code: 'fence-1x4',
    name: 'Fence',
    category: 'decorative',
    studsX: 1,
    studsY: 4,
    defaultColour: C.decorative,
  },
  {
    code: 'flag-2x2',
    name: 'Flag',
    category: 'decorative',
    studsX: 2,
    studsY: 2,
    defaultColour: C.decorative,
  },
  {
    code: 'eye-1x1',
    name: 'Eye tile',
    category: 'decorative',
    studsX: 1,
    studsY: 1,
    defaultColour: C.decorative,
  },
  {
    code: 'antenna-1x1',
    name: 'Antenna',
    category: 'decorative',
    studsX: 1,
    studsY: 1,
    defaultColour: C.decorative,
  },
  {
    code: 'wheel-2x2',
    name: 'Wheel',
    category: 'decorative',
    studsX: 2,
    studsY: 2,
    defaultColour: C.decorative,
  },

  // Figure parts (6)
  {
    code: 'figure-head',
    name: 'Figure head',
    category: 'figure',
    studsX: 1,
    studsY: 1,
    defaultColour: C.figure,
  },
  {
    code: 'figure-torso',
    name: 'Figure torso',
    category: 'figure',
    studsX: 2,
    studsY: 2,
    defaultColour: C.figure,
  },
  {
    code: 'figure-leg',
    name: 'Figure leg',
    category: 'figure',
    studsX: 1,
    studsY: 2,
    defaultColour: C.figure,
  },
  {
    code: 'figure-arm',
    name: 'Figure arm',
    category: 'figure',
    studsX: 1,
    studsY: 2,
    defaultColour: C.figure,
  },
  {
    code: 'figure-hand',
    name: 'Figure hand',
    category: 'figure',
    studsX: 1,
    studsY: 1,
    defaultColour: C.figure,
  },
  {
    code: 'figure-hat',
    name: 'Figure hat',
    category: 'figure',
    studsX: 1,
    studsY: 1,
    defaultColour: C.figure,
  },

  // Connectors and annotation (4)
  {
    code: 'connector-line',
    name: 'Connector line',
    category: 'connector',
    studsX: 1,
    studsY: 4,
    defaultColour: C.connector,
  },
  {
    code: 'connector-arrow',
    name: 'Connector arrow',
    category: 'connector',
    studsX: 1,
    studsY: 4,
    defaultColour: C.connector,
  },
  {
    code: 'connector-bracket',
    name: 'Connector bracket',
    category: 'connector',
    studsX: 2,
    studsY: 4,
    defaultColour: C.connector,
  },
  {
    code: 'label-1x2',
    name: 'Label tile',
    category: 'connector',
    studsX: 1,
    studsY: 2,
    defaultColour: C.connector,
  },

  // Specialty (4)
  {
    code: 'bracket-1x2',
    name: 'Bracket',
    category: 'specialty',
    studsX: 1,
    studsY: 2,
    defaultColour: C.specialty,
  },
  {
    code: 'hinge-1x2',
    name: 'Hinge',
    category: 'specialty',
    studsX: 1,
    studsY: 2,
    defaultColour: C.specialty,
  },
  {
    code: 'plate-round-2x2',
    name: '2 by 2 round plate',
    category: 'specialty',
    studsX: 2,
    studsY: 2,
    defaultColour: C.specialty,
  },
  {
    code: 'baseplate-8x8',
    name: '8 by 8 baseplate',
    category: 'specialty',
    studsX: 8,
    studsY: 8,
    defaultColour: C.specialty,
  },
] as const;

if (CANONICAL_BRICKS.length !== 52) {
  throw new Error(`Canonical brick set must have 52 entries, got ${CANONICAL_BRICKS.length}`);
}

export function findCanonicalBrick(code: string): BrickDefinition | undefined {
  return CANONICAL_BRICKS.find((b) => b.code === code);
}
